[package]
name = "aurora-engine"
version = "0.0.0"
authors = ["NEAR <hello@near.org>"]
edition = "2018"
description = ""
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-engine"
repository = "https://github.com/aurora-is-near/aurora-engine"
license = "CC0-1.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
debug = false
debug-assertions = false
overflow-checks = true
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[dependencies]
borsh = { version = "0.8.2", default-features = false }
evm = { git = "https://github.com/aurora-is-near/sputnikvm", rev = "f90f843", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
primitive-types = { version = "0.9.0", default-features = false, features = ["rlp"] }
rlp = { version = "0.5.0", default-features = false }
sha3 = { version = "0.9.1", default-features = false }
wee_alloc = { version = "0.4.5", default-features = false }

[dev-dependencies]
hex = "0.4.3"

[features]
default = ["std"]
std = ["borsh/std", "evm/std", "lazy_static/std", "primitive-types/std", "rlp/std", "sha3/std"]
contract = ["lazy_static/spin_no_std"]
