---
on: [push]
name: Builds
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install the toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-01-30
          override: true
      - run: make release
      - run: ls -lH release.wasm
      - name: Upload release.wasm
        uses: actions/upload-artifact@v2
        with:
          name: release.wasm
          path: release.wasm
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install the toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-01-30
          override: true
      - run: make debug
      - run: ls -lH debug.wasm
      - name: Upload debug.wasm
        uses: actions/upload-artifact@v2
        with:
          name: debug.wasm
          path: debug.wasm
